export const dummyScoreData = [
  {
    id: 'hole',
    label: "Hole",
    bgColor: "#4F4F4F",
    textColor: "white",
    fontWeight: "bold",
    fontSize: 14,
    value: Array.from({ length: 18 }, (_, i) => ({
      holeNo: i + 1,
      val: i + 1,
      textColorImp: 'white',
      textCircleColor: '#4F4F4F',
    })),
  },
  {
    id: 'par',
    label: "PAR",
    bgColor: "#ECF2F5",
    textColor: "black",
    fontWeight: "bold",
    fontSize: 14,
    value: [
      { holeNo: 1, val: 420, textColorImp: 'green', textCircleColor: 'pink' },
      { holeNo: 2, val: 520, textColorImp: 'red', textCircleColor: 'yellow' },
      { holeNo: 3, val: 390, textColorImp: 'blue', textCircleColor: 'lightblue' },
      { holeNo: 4, val: 350 },
      { holeNo: 5, val: 450 },
      { holeNo: 6, val: 300 },
      { holeNo: 7, val: 480 },
      { holeNo: 8, val: 420 },
      { holeNo: 9, val: 400 },
      { holeNo: 10, val: 390 },
      { holeNo: 11, val: 440 },
      { holeNo: 12, val: 370 },
      { holeNo: 13, val: 410 },
      { holeNo: 14, val: 430 },
      { holeNo: 15, val: 450 },
      { holeNo: 16, val: 460 },
      { holeNo: 17, val: 470 },
      { holeNo: 18, val: 490 },
    ],
  },
  {
    id: 'yard',
    label: "Yard",
    value: Array.from({ length: 18 }, (_, i) => ({
      holeNo: i + 1,
      val: 400 + i * 5,
      textColorImp: 'black',
      textCircleColor: 'white',
    })),
  },
  {
    id: 'name',
    label: "Dinesh",
    bgColor: "#F4F4F4",
    textColor: "black",
    fontWeight: "bold",
    fontSize: 14,
    value: Array.from({ length: 18 }, (_, i) => ({
      holeNo: i + 1,
      val: Math.floor(Math.random() * 3) + 3,
      textColorImp: 'white',
      textCircleColor: 'green',
    })),
  },
  {
    id: 'putts',
    label: "Putts",
    value: Array.from({ length: 18 }, (_, i) => ({
      holeNo: i + 1,
      val: Math.floor(Math.random() * 3) + 1,
    })),
  },
  {
    id: 'fir',
    label: "FIR",
    value: Array.from({ length: 18 }, (_, i) => ({
      holeNo: i + 1,
      val: Math.random() > 0.5 ? 1 : 0,
    })),
  },
  {
    id: 'reg',
    label: "REG",
    value: Array.from({ length: 18 }, (_, i) => ({
      holeNo: i + 1,
      val: Math.random() > 0.5 ? 1 : 0,
    })),
  },
  {
    id: 'upDown',
    label: "UP/Down",
    value: Array.from({ length: 18 }, (_, i) => ({
      holeNo: i + 1,
      val: Math.random() > 0.5 ? 1 : 0,
    })),
  },
  {
    id: 'penalty',
    label: "Penalty",
    value: Array.from({ length: 18 }, (_, i) => ({
      holeNo: i + 1,
      val: Math.random() > 0.8 ? 1 : 0,
    })),
  },
];